[33mcommit 6b20d520440da5ddd8599026a9da1059e6bec7db[m[33m ([m[1;36mHEAD -> [m[1;32mmaster[m[33m)[m
Author: Morales Andrés <andresmoralesjulian@gmail.com>
Date:   Mon Nov 20 20:05:25 2023 -0300

    segundo aumento, agregado de color para notas y primer background changer

[33mcommit 42fa6353603f1415f05c3491d6280e7e2d6a10d2[m
Author: Morales Andrés <andresmoralesjulian@gmail.com>
Date:   Sun Nov 19 19:43:59 2023 -0300

    version preliminar
